### ISSUE TITLE
session_start() add Set-Cookie header

### ISSUE THREAD

**Issue by danielspk** [middlewares/aura-session#1]
Hi.

When *session_start()* is executed it adds the *Set-Cookie* header, which is not compatible with PSR-7.

Should not the *session_start()* with the *use_cookies* option be set to false to avoid this behavior and set the *Set-Cookie* header manually using the *withHeader()* method of the response object?

Thanks.

**Comment by oscarotero** [comment]
Hi.
I'm agree, but it is something that only can be done in [Aura.Session](https://github.com/auraphp/Aura.Session) package, so you should create this issue in that repository.
Thanks!

**Comment by danielspk** [comment]
Thanks
